name: Terraform CI

on:
  push:
    branches:
      - feature-branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: environments/preprod

    steps:                        # GitHub Actions runner/temporary machine par tumhara GitHub repository ka code download/checkout karo.
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install Checkov
        run: pip install checkov  

      - name: Checkov Version
        run: checkov --version  

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: TFLint Version
        run: tflint --version  

      - name: Checkov Scan
        working-directory: .
        run: checkov -d .

      # - name: Terraform Plan
      #   run: terraform plan